apiVersion: v1
kind: Service
metadata:
  name: nginx-custom-service
spec:
  type: NodePort
  selector:
    app: nginx-custom
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
